# This version of config.mk was generated by:
# ./configure --prefix=/Users/anuj.patel/local
# Any changes made here will be lost if configure is re-run
SRCDIR = .
PREFIX = /Users/anuj.patel/local
EXEC_PREFIX = $(PREFIX)
BINDIR = $(EXEC_PREFIX)/bin
MANPREFIX = $(PREFIX)/share/man
CC = cc
CFLAGS = -pipe -Os -ffunction-sections -fdata-sections -fPIE
LDFLAGS = 
CFLAGS_STD = -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DNDEBUG -D_FORTIFY_SOURCE=2 -D_DARWIN_C_SOURCE
LDFLAGS_STD = -lc -lutil
CFLAGS_AUTO = -fstack-protector-all
LDFLAGS_AUTO = 
CFLAGS_DEBUG = -U_FORTIFY_SOURCE -UNDEBUG -O0 -g -ggdb -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-sign-compare
